# Generated by Django 6.1.1 on 2026-09-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_organization_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
