# Generated by Django 6.1.1 on 2026-09-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_client_metadata_product_metadata_supplier_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
