# Generated by Django 6.1.1 on 2026-09-15 09:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_product_sku_per_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(blank=True, max_length=200, null=True)),
                ('fournisseur', models.CharField(blank=True, max_length=200, null=True)),
                ('categorie', models.CharField(blank=True, max_length=100, null=True)),
                ('modePaiement', models.CharField(blank=True, max_length=50, null=True)),
                ('referenceFacture', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('montantHt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxePct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='api.organization')),
            ],
        ),
    ]
