# Generated by Django 6.1.1 on 2026-09-15 09:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_depense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avoir',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client', models.CharField(max_length=200)),
                ('facture', models.CharField(blank=True, max_length=100, null=True)),
                ('motif', models.TextField(blank=True, null=True)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(default='Émis', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avoirs', to='api.organization')),
            ],
        ),
    ]
