# Generated by Django 6.1.1 on 2026-09-15 09:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_avoir'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonCommande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bc_number', models.CharField(max_length=50)),
                ('fournisseur', models.CharField(max_length=200)),
                ('statut', models.CharField(default='Brouillon', max_length=30)),
                ('dateEmission', models.DateField(blank=True, null=True)),
                ('livraisonPrevue', models.DateField(blank=True, null=True)),
                ('conditionsPaiement', models.CharField(blank=True, max_length=100, null=True)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('articles', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_commande', to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='BulletinPaie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employeId', models.CharField(max_length=100)),
                ('periode', models.CharField(max_length=50)),
                ('dateEmission', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(default='Brouillon', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins_paie', to='api.organization')),
            ],
        ),
    ]
