# Generated by Django 6.1.1 on 2026-09-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_boncommande_bulletinpaie'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='bank_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='capital_social',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='cnss',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
