# Generated by Django 6.1.1 on 2026-09-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_invoice_client_alter_quotation_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
